const esDocuments = {
    NC: [
        {
            type: 'first_type',
            firstname: 'First_Name',
            lastname: 'Last_Name',
            birthday: 'Birth_Date',
            gender: 'Gender',
            phone: 'Phone10',
            address: 'Address_Line',
            state: 'State',
            city: 'City',
            zip: 'Zip',
            extraAddressLine: 'Extra_Address_Line',
            congressionalDistrict: 'Congressional_District',
        },
        {
            type: 'second_type',
            firstname: 'first_name',
            lastname: 'last_name',
            birthday: 'birth_year',
            gender: 'gender_code',
            phone: 'full_phone_number',
            address: 'res_street_address',
            state: 'state_cd',
            city: 'res_city_desc',
            zip: 'zip_code',
            congressionalDistrict: 'cong_dist_abbrv',
            voterRegistrationNumber: 'voter_reg_num',
            voterStatusDesc: 'voter_status_desc',
            voterStatusReasonDesc: 'voter_status_reason_desc',
        }
    ],
    CO: [
        {
            type: 'colorado',
            firstname: 'FIRST_NAME',
            lastname: 'LAST_NAME',
            address: 'RESIDENTIAL_ADDRESS',
            state: 'RESIDENTIAL_STATE',
            city: 'RESIDENTIAL_CITY',
            zip: 'RESIDENTIAL_ZIP_CODE',
            zipPlus: 'RESIDENTIAL_ZIP_PLUS',
            mailAddr1: 'MAIL_ADDR1',
            mailAddr2: 'MAIL_ADDR2',
            mailAddr3: 'MAIL_ADDR3',
            mailingCity: 'MAILING_CITY',
            mailingState: 'MAILING_STATE',
            mailingZipCode: 'MAILING_ZIP_CODE',
            mailingZipPlus: 'MAILING_ZIP_PLUS',
            mailingCountry: 'MAILING_COUNTRY',
            congressionalDistrict: 'CONGRESSIONAL',
            voterRegistrationNumber: 'VOTER_ID',
            phone: 'PHONE_NUM',
            birthday: 'BIRTH_YEAR',
            gender: 'GENDER',
            voterStatusDesc: 'STATUS',
            voterStatusReasonDesc: 'STATUS_REASON',
        }
    ],
    WA: [
        {
            type: 'washington',
            firstname: 'FName',
            lastname: 'LName',
            address: 'RegAddress',
            state: 'RegState',
            city: 'RegCity',
            zip: 'RegZipCode',
            mailAddr1: 'Mail1',
            mailAddr2: 'Mail2',
            mailAddr3: 'Mail3',
            mailAddr4: 'Mail4',
            mailingCity: 'MailCity',
            mailingState: 'MailState',
            mailingZipCode: 'MailZip',
            mailingCountry: 'MailCountry',
            congressionalDistrict: 'CongressionalDistrict',
            voterRegistrationNumber: 'StateVoterID',
            birthday: 'Birthdate',
            gender: 'Gender',
            voterStatusDesc: 'StatusCode'
        }
    ],
    SF: [
        {
            type: 'sanfrancisco',
            firstname: 'szNameFirst',
            lastname: 'szNameLast',
            address: 'szSitusAddress',
            state: 'sSitusState',
            city: 'szSitusCity',
            zip: 'sSitusZip',
            mailAddr1: 'szMailAddress1',
            mailAddr2: 'szMailAddress2',
            mailAddr3: 'szMailAddress3',
            mailAddr4: 'szMailAddress4',
            mailingZipCode: 'szMailZip',
            congressionalDistrict: 'sDistrictID_0',
            voterRegistrationNumber: 'VoterUniqueID',
            phone: 'szPhone',
            birthday: 'dtBirthDate',
            gender: 'sGender',
            voterStatusDesc: 'sStatusCode',
            voterStatusReasonDesc: 'szStatusReasonDesc'
        }
    ],
};

module.exports = esDocuments;
